feat: health check api (watcher)
lablup/backend.ai-agent pull request #241
Opened 2020-11-08 03:47 UTC by adrysn

2020-11-20 06:46 UTC, achimnol requested changes
nvidia-smi supports CSV-formatted outputs for programmatic consumption.
Please consider using that output:
```
> nvidia-smi --format=csv --query-gpu=index,name,uuid,driver_version,memory.total,memory.used,utilization.gpu,utilization.memory --no-units
index, name, uuid, driver_version, memory.total [MiB], memory.used [MiB], utilization.gpu [%], utilization.memory [%]
0, Tesla V100-SXM3-32GB, GPU-02ba5a4d-2829-ebf7-e613-083e8b62dbb5, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
1, Tesla V100-SXM3-32GB, GPU-385c62a7-0a95-cce5-81a8-2c9c5d5a7f6c, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
2, Tesla V100-SXM3-32GB, GPU-3c6b25e5-f7b9-ffc9-2c3c-386586c0778b, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
3, Tesla V100-SXM3-32GB, GPU-0e89496d-bcbf-b990-ed48-3859751f5db2, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
4, Tesla V100-SXM3-32GB, GPU-331cc9a6-dfc2-3b04-c8b0-f004d14e0483, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
5, Tesla V100-SXM3-32GB, GPU-3cd84123-d9ff-6032-1bc7-ab191f7a980c, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
6, Tesla V100-SXM3-32GB, GPU-361a9076-6bcc-3875-771b-411116e1ce63, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
7, Tesla V100-SXM3-32GB, GPU-fdd89a92-8b04-f092-3e07-b434249a0542, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
8, Tesla V100-SXM3-32GB, GPU-d929421b-3377-39c0-b9b2-474ee68afb10, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
9, Tesla V100-SXM3-32GB, GPU-3caa4672-eb42-1b6a-9857-d520fb715484, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
10, Tesla V100-SXM3-32GB, GPU-529aa577-f39c-ca7f-5162-ce888a2fecbc, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
11, Tesla V100-SXM3-32GB, GPU-5318f22e-03eb-0ae6-6b8f-f7be360fb3c2, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
12, Tesla V100-SXM3-32GB, GPU-1ca51595-f08d-c2f2-1655-7e53908d7730, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
13, Tesla V100-SXM3-32GB, GPU-3a0319d2-a635-eb2e-b105-32c38916f300, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
14, Tesla V100-SXM3-32GB, GPU-6f3d0fce-31b4-fc44-df3d-ca81a88aea72, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
15, Tesla V100-SXM3-32GB, GPU-bf934fea-6ded-5377-5804-672911facb2b, 418.126.02, 32480 MiB, 13 MiB, 0 %, 0 %
```

2020-11-24 08:17 UTC, adrysn commented
Updated to return GPU detail information if found.

2020-11-29 17:49 UTC, achimnol commented on src/ai/backend/agent/watcher.py
> +        gpu_items = gpu_info.split(', ')
Python has an intrinsic CSV parser, which handles a few more edge cases such as quotes and escapes.
How about using it?
ref) https://docs.python.org/3/library/csv.html

2020-12-13 16:19 UTC, adrysn commented on src/ai/backend/agent/watcher.py
> +        gpu_items = gpu_info.split(', ')
Replaced the csv parsing logic to use csv module in the standard library.

2021-11-26 02:45 UTC, adrysn commented
This is deprecated in favor of https://github.com/lablup/backend.ai-watcher.

2021-11-26 02:45 UTC, closed without merging