feat: Add status info of OOM
lablup/backend.ai-agent pull request #304
Opened 2021-09-06 09:38 UTC by youngjun0627

### issue
https://github.com/lablup/backend.ai/issues/265

### idea
I obtain kernel's status info from docker-events-subscriber. Event-data from the subscriber contains 'Action' key, that means 'create' or 'die' or 'oom'. When Out-of-memory occurs in a kernel, 'Action' key contains value of 'oom'. if check that, I insert status info of 'oom' to kernel_object's termination_reason. And, update column of status_info from kernels table.

### result
I test my code using [BFS algorithm](https://www.acmicpc.net/problem/1726). I generate test-case, and two solution code, one of them is efficient in terms of memory, the other is not. Fllowing images show difference results.

- efficient code : 
![image](https://user-images.githubusercontent.com/57058726/132195696-a458516c-e666-480e-b04a-c4e49d1fbf7d.png)

- not efficient code:
![image](https://user-images.githubusercontent.com/57058726/132195577-e34c2727-4a44-40e5-a6e4-1777c8207cc4.png)

2021-09-06 12:53 UTC, achimnol requested changes

2021-09-06 12:53 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                        if evdata['Action']=='oom':
Please keep PEP-8 code style.

2021-09-06 12:53 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                            kernel_obj.termination_reason = 'outofmemory'
The reason uses a "kebab-case" style. Let's change it to `'out-of-memory'`.

2021-09-06 12:56 UTC, achimnol commented
I have questions:
* Do both events ("oom" and "die") happen for a container killed by oom?
* If so, is the order of "oom" and "die" always consistent?

2021-09-06 13:55 UTC, youngjun0627 commented
Yes, OOM killer decides to kill the container when catching out-of-memory. So, the order is 'create -> start -> oom -> kill -> die -> stop -> destroy'

2021-09-06 13:58 UTC, youngjun0627 commented on src/ai/backend/agent/docker/agent.py
> +                            kernel_obj.termination_reason = 'outofmemory'
I have finished to change it!

2021-09-08 08:00 UTC, achimnol commented
Thanks for the answers.
I'm just worried about whether the termination reason is overwritten or not.
Have you confirmed from the client by checking the `status_info` field of sessions?

2021-09-08 10:22 UTC, youngjun0627 commented
I have a question.
- if the container has many process,  OOM killer remove one or some processes.  Then, will we decided to terminate the container? If not, the container maintains status of 'RUNNING' and stays until client requests to destroy it.

The implemented code updates column of status-info on 'kernels' table. But, because the container is terminated by client-destroy-request, status-info of 'user-requested' is displayed to client.

2021-09-08 15:05 UTC, achimnol commented
Ah... then, can the OOM event occur *multiple* times for a single container? Hm.........

2021-09-08 16:37 UTC, youngjun0627 commented
Yes.
For example, if three processes(task) run in a container and OOM event occurs **(one)**, OOM killer chooses to terminate one or more of them according to priority. 
After one process is removed by OOM killer, if another process is out-of-memory, OOM event occurs **(two)** and OOM killer does it.
Finally, if the other process is not out-of-memory, the container has one-process is running . And if not **(three)**, the container does not have a process, but it is running.
**OOM killer removes process(task), not container.** 
However, I think all the task in kernel made by client is important. So, what do you think about terminating the container immediately when it finds 'oom'?

2021-09-11 06:53 UTC, achimnol commented
Directly killing the container upon every OOM events may be too harsh for some deep learning workloads such as PyTorch, as @inureyes says on a discussion with him.
We might need to add a new feature such as setting a shell command for each session to be executed when OOM occurs, so that we could specify user-defined recovery actions. Just let's hold the issue until we make design decision.

2021-09-11 07:02 UTC, achimnol commented
Please resolve the conflicts, checking the functionality of recent main branch updates such as #299, #300, #301.

2021-09-22 10:13 UTC, youngjun0627 commented
- Idea
when OOM event occurs, container is paused(of course, status-info is 'out-of-memory').
The user checks the sesision status and unpauses or restarts the container after the problem is solved.
So, I suggest we add a command option(unpause) and a container status('PAUSED')

2021-10-02 09:49 UTC, youngjun0627 commented
![image](https://user-images.githubusercontent.com/57058726/135711074-18979efd-6737-403d-a37c-3145bc0cf854.png)

I add 'paused' and 'unpaused' status for client to recover it when 'OOM' occurs. For this idea, we need to add PausedEvent and the handler of this. I wonder your idea about this issue or feedback from my solution.

2022-08-12 04:57 UTC, achimnol commented
Migrated to lablup/backend.ai#629.

2022-08-12 04:57 UTC, closed without merging