feat: Add RPC method to update scaling_group of agents table
lablup/backend.ai-agent pull request #327
Opened 2021-12-30 13:05 UTC by yujung7768903

resolve https://github.com/lablup/backend.ai/issues/317

manager component can update scaling_group of agents table by calling this PRC method.

## Test
* I tested it by requesting to change the scaling group from "default" to "test".
* When performing the handle_heartbeat() method of registry of manager, I print scaling group to check if the scaling group has changed.
```
async def handle_heartbeat(self, agent_id, agent_info):
        ...
        sgroup = agent_info.get('scaling_group', 'default')
        print('sgroup:', sgroup) # Add this line to check
        ...
        # Check and update status of the agent record in DB
            async def _update() -> None:
                nonlocal instance_rejoin
                async with self.db.begin() as conn:
                    fetch_query = (
                        sa.select([...])
                        .select_from(agents)
                        .where(agents.c.id == agent_id)
                        .with_for_update()
                    )
                    result = await conn.execute(fetch_query)
                    row = result.first()
                    ...
```
## When manager call this RPC method
* manager (scaling_group: "default" -> "test")
<img width="829" alt="Screen Shot 2021-12-30 at 9 56 14 PM" src="https://user-images.githubusercontent.com/68562176/147753883-05cab189-3bb3-4265-aa42-4d839321341c.png">
* agent
<img width="860" alt="Screen Shot 2021-12-30 at 10 01 37 PM" src="https://user-images.githubusercontent.com/68562176/147754297-6d7eb47c-c9b3-4935-9288-ccef1576e01b.png">
* agent.toml
<img width="479" alt="Screen Shot 2021-12-30 at 10 02 20 PM" src="https://user-images.githubusercontent.com/68562176/147754358-78f290d8-55fb-4c20-a41d-6d578d163459.png">

2021-12-31 01:34 UTC, adrysn commented
Great to have this feature which is requested from some customers. I have some opinions.

1. We need to update `setup.cfg` to explicitly state the `tomlkit` is a dependent package.
2. `dump` and `load` is too general terms so how about to `import tomlkit` and replace the terms with `tomlkit.dump` and `tomlkit.load`: https://github.com/lablup/backend.ai-agent/pull/327/files#diff-f12f61c545fb5900632fc6677ccd5ac7ba37d221a52907eedeb4b5832aa52218R3

2021-12-31 06:30 UTC, yujung7768903 commented
> Great to have this feature which is requested from some customers. I have some opinions.
> 
> 1. We need to update `setup.cfg` to explicitly state the `tomlkit` as a dependent package.
> 2. `dump` and `load` is too general terms so how about to `import tomlkit` and replace the terms with `tomlkit.dump` and `tomlkit.load`: https://github.com/lablup/backend.ai-agent/pull/327/files#diff-f12f61c545fb5900632fc6677ccd5ac7ba37d221a52907eedeb4b5832aa52218R3

2021-12-31 07:00 UTC, yujung7768903 commented
> Great to have this feature which is requested from some customers. I have some opinions.
> 
> 1. We need to update `setup.cfg` to explicitly state the `tomlkit` as a dependent package.
> 2. `dump` and `load` is too general terms so how about to `import tomlkit` and replace the terms with `tomlkit.dump` and `tomlkit.load`: https://github.com/lablup/backend.ai-agent/pull/327/files#diff-f12f61c545fb5900632fc6677ccd5ac7ba37d221a52907eedeb4b5832aa52218R3

I updated it referring to your comment!

2022-01-16 07:41 UTC, achimnol requested changes

2022-01-16 07:41 UTC, achimnol commented on .github/workflows/default.yml
> +        python -m pip install -U pip setuptools tomlkit
Dependencies should be added to `setup.cfg` only. Please remove `tomlkit` from the workflows!

FYI: Updating `pip` and `setuptools` manually is to ensure latestness of the package installation toolchain because older versions may have errors when detecting compatibility of the host platform and wheel packages.

2022-01-21 07:58 UTC, yujung7768903 commented on .github/workflows/default.yml
> +        python -m pip install -U pip setuptools tomlkit
I removed tomlkit from workflows!

2022-01-21 09:34 UTC, achimnol approved these changes
LGTM!

2022-01-21 09:38 UTC, merged