feat: make container metadata server structure extensible
lablup/backend.ai-agent pull request #333
Opened 2022-01-13 07:30 UTC by kyujin-cho

This PR introduces modularized metadata server feature by rewriting metadata server as plugin structure. Check out lablup/backend.ai-internal#16 for more details.

2022-01-26 03:17 UTC, achimnol requested changes

2022-01-26 03:17 UTC, achimnol commented on src/ai/backend/agent/docker/metadata/plugin.py
> +            Tuple[web.Application, Sequence[WebMiddleware], Mapping[str, Any]]:
How about using `typing.NamedTuple` to shorten the type annotation of return values and make the meaning of each field to stand out with explicit names?

2022-01-26 03:17 UTC, achimnol commented on src/ai/backend/agent/docker/metadata/plugin.py
> +            structure_pointer = structure
Why yet another variable alias instead of directly using `structure`?

2022-01-26 03:17 UTC, achimnol commented on src/ai/backend/agent/docker/metadata/plugin.py
> +# TODO: Split out metadata server as seperate backend.ai plugin
I think it is okay to have the "root" metadata server plugin inside the agent package, but it may be better to do so with a separate module such as `ai.backend.agent.docker.metadata.root`.

2022-01-26 03:17 UTC, achimnol commented on src/ai/backend/agent/docker/metadata/plugin.py
> +
I think we could add a abstract class variable that specifies `route_prefix` to allow namespacing of plugins.

2022-01-26 03:17 UTC, achimnol commented on src/ai/backend/agent/utils.py
> +                log.debug('Container ID does not match')
Let's wrap these debug logs with an option to enable it, e.g., `debug.log-pidmap` in `agent.toml`, because it might be too verbose in some configurations.

Example:
![image](https://user-images.githubusercontent.com/555156/151098192-ebb6a0b6-b424-46b7-b7ee-8e46ed54cef7.png)

2022-01-27 06:03 UTC, kyujin-cho commented on src/ai/backend/agent/docker/metadata/plugin.py
> +            structure_pointer = structure
I've added a brief explanation comment about `structure_pointer` in code.

2022-01-27 06:04 UTC, kyujin-cho commented on src/ai/backend/agent/docker/metadata/plugin.py
> +
similar feature already supported when declaring plugin at each package's `setup.cfg`. each entrypoint name will be used as route prefix.

2022-08-12 05:00 UTC, achimnol commented
Replaced with lablup/backend.ai#448

2022-08-12 05:00 UTC, closed without merging