Copy backup file during dump agent.toml
lablup/backend.ai-agent pull request #339
Opened 2022-01-24 05:31 UTC by jil8885

This pull reqeust resolves https://github.com/lablup/backend.ai/issues/349
Copy agent,toml to agent.toml.bak and dump new config into agent.toml

2022-01-26 03:43 UTC, achimnol requested changes

2022-01-26 03:43 UTC, achimnol commented on src/ai/backend/agent/server.py
> +            shutil.copy(cfg_src_path, f"{cfg_src_path}.bak")
It is kind-of safer to copy the file before opening it.
```suggestion
        shutil.copy(cfg_src_path, f"{cfg_src_path}.bak")
        with open(cfg_src_path, 'w') as f:
```

And let's wrap the method body using [an executor](https://docs.python.org/3.10/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) and `asyncio.Lock` to keep it async and prevent potential races on updates.

2022-01-26 03:43 UTC, achimnol commented on changes/339.feature
> +Copy agent.toml to agent.toml.bak before dump new config into agent.toml
```suggestion
Copy `agent.toml` to `agent.toml.bak` before modifying it to update the scaling group
```

2022-02-08 16:43 UTC, achimnol commented on src/ai/backend/agent/server.py
>  import tomlkit
Please move these imports to follow the alphabetical order and distinguishable sections of stdlib, 3rd party libs, other pkgs under the same `ai.backend` namespace, and internal relative imports.

2022-02-09 01:20 UTC, jil8885 commented on src/ai/backend/agent/server.py
>  import tomlkit
Resolved at https://github.com/lablup/backend.ai-agent/pull/339/commits/cb2ee1c487dc952debe583c95069ec8f3668f0d5

2022-02-09 08:44 UTC, achimnol requested changes

2022-02-09 08:44 UTC, achimnol commented on src/ai/backend/agent/server.py
> +import shutil
T_T
Since `shutil` is a stdlib, it should be placed on the upper block, before `import signal`.

2022-02-10 01:55 UTC, jil8885 commented on src/ai/backend/agent/server.py
> +import shutil
I forgot it is stdlib, so I rearrange it with other stdlib at https://github.com/lablup/backend.ai-agent/pull/339/commits/6435abd7e7a36c9afc3ea70c5b7a27f9c0f497cd

2022-03-02 14:36 UTC, merged