fix: remove asyncio.shield from agent
lablup/backend.ai-agent pull request #341
Opened 2022-02-17 04:16 UTC by jil8885

* Wrap create_task under asyncio.shield to control when async job is finished
* Related to https://github.com/lablup/backend.ai/issues/359

2022-02-24 08:46 UTC, achimnol requested changes

2022-02-24 08:46 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                                    ))
**This should not be indented.** It will create a critical bug in production where `log-docker-events` is disabled: all session creation and termination get stuck.

2022-02-24 08:54 UTC, jil8885 commented on src/ai/backend/agent/docker/agent.py
> +                                    ))
https://github.com/lablup/backend.ai-agent/pull/341/commits/08399a661be16da5d385e82f4ed56b2b3a1c62ae resoves this issue.

2022-02-24 08:58 UTC, achimnol requested changes
Where are calls to `.shutdown()` of presistent task groups?

2022-02-25 06:32 UTC, achimnol requested changes

2022-02-25 06:32 UTC, achimnol commented on src/ai/backend/agent/kubernetes/agent.py
> +                await self.kubernetes_ptask_group.shutdown()
To maintain consistency with the docker backend, this should be moved to the upper line of `super().shutdown()`.  It is also better to clean up private resources first and then clean up the inherited resourcse.

2022-02-25 06:32 UTC, achimnol commented on src/ai/backend/agent/kubernetes/agent.py
> +    agent_ptask_group: aiotools.PersistentTaskGroup
Shouldn't this be named as `kubernetes_ptask_group`?
How about renaming as `k8s_ptask_group`?

2022-02-25 06:32 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +    agent_ptask_group: aiotools.PersistentTaskGroup
Shouldn't this named as `docker_ptask_group`?

2022-02-25 06:56 UTC, achimnol approved these changes
LGTM

2022-02-25 07:05 UTC, merged