feat: Add subdirectory host path based on root folder
lablup/backend.ai-agent pull request #343
Opened 2022-02-17 16:15 UTC by SonMinWoo

resolves: https://github.com/lablup/backend.ai/issues/360
related: https://github.com/lablup/backend.ai-manager/pull/537

**Let's allow using a "partial" view of a vfolder inside sessions.
For example, if a vfolder mystuff has a/b/c subdirectories, let's allow mounting mystuff/a/b as /home/work/bbb.**
![issue360](https://user-images.githubusercontent.com/31719811/154523230-901e93e0-6f7e-4cd4-b348-148ed20342f8.png)

2022-02-18 08:42 UTC, achimnol requested changes

2022-02-18 08:42 UTC, achimnol commented on src/ai/backend/agent/agent.py
> +            host_path = Path(folder_path + re.sub("[/]+", "/", folder_name).partition("/")[2])
Is it really necessary to use regular expressions here?
The code is not understandable at a first glance.
Please make it to expose its intention more clearly.

2022-02-18 08:42 UTC, achimnol commented on changes/343.feature
> +Add subdirectory host path based on root folder
What do you mean by "based on" here?

2022-02-21 01:58 UTC, SonMinWoo commented on src/ai/backend/agent/agent.py
> +            host_path = Path(folder_path + re.sub("[/]+", "/", folder_name).partition("/")[2])
Yes. Regular expressions is not necessary. It is deleted.

2022-02-21 02:00 UTC, SonMinWoo commented on changes/343.feature
> +Add subdirectory host path based on root folder
This expression is ambiguous. So it changed to explain more specific feature.

2022-02-22 02:52 UTC, achimnol requested changes

2022-02-22 02:52 UTC, achimnol commented on src/ai/backend/agent/agent.py
> +            host_path = Path(str(host_path) + "/" + folder_name.partition("/")[2])
Is it necessary cast `host_path` to `str`?
`pathlib.Path` provides `/` operator for pathname concatenation.

Also consider rename `folder_name` variable because it no longer only contains the vfolder name but its subdirectory path as well.
What would be a good name?

2022-02-22 03:10 UTC, SonMinWoo commented on src/ai/backend/agent/agent.py
> +            host_path = Path(str(host_path) + "/" + folder_name.partition("/")[2])
how about folder_path?

2022-03-10 14:21 UTC, merged