fix: automatic round-down to quantum size
lablup/backend.ai-agent pull request #349
Opened 2022-03-18 03:37 UTC by kyujin-cho

This PR resolves lablup/backend.ai-internal#34

2022-03-21 05:20 UTC, achimnol requested changes

2022-03-21 05:20 UTC, achimnol commented on src/ai/backend/agent/agent.py
> +            log.exception("unexpected error in lifecycle task", exc_info=exc_obj)
No need to fix but just FYI: As of aiotools 1.5, this exception handler is executed under an `except` block context, you may simply omit `exc_info` kwarg to `log.exception()` so that it automatically picks up `sys.exc_info()`.

2022-03-21 05:20 UTC, achimnol commented on src/ai/backend/agent/resources.py
> +    return from_dec - remainder
Shall we just replace this with `Decimal.quantize()`?
Is there other reason to keep a custom implementation?

2022-03-21 05:20 UTC, achimnol commented on src/ai/backend/agent/resources.py
> +                actual_alloc[dev_id] = rounded_val
For simplicity, we could just assign the rounded down value, instead of applying the difference between the original and rounded values.

2022-03-21 05:20 UTC, achimnol commented on src/ai/backend/agent/server.py
> +            _subnet_hint = None
This part looks irrelevant to the issue. Please make it as another issue and/or PR.

2022-03-21 05:20 UTC, achimnol commented on src/ai/backend/agent/utils.py
> +            local_ipaddrs = [*identity.fetch_local_ipaddrs(_subnet)]
Same here.

2022-03-21 05:20 UTC, achimnol commented on tests/test_alloc_map.py
> +    with pytest.raises(NotMultipleOfQuantum, match='actual calculated amount is zero'):
👍🏼

2022-03-22 04:09 UTC, kyujin-cho commented on src/ai/backend/agent/resources.py
> +    return from_dec - remainder
`Decimal.quantize()` won't work as we expected before.   
<img width="369" alt="Screen Shot 2022-03-22 at 1 08 02 PM" src="https://user-images.githubusercontent.com/2904494/159406147-ee1d0cf5-e83e-42d3-b4b5-3285704c2b07.png">
In this case, we need `Decimal('0.5')` as nearest round-down value of `0.67`; but `Decimal.quantize()` returns `0.67`.

2022-03-23 08:19 UTC, achimnol commented on src/ai/backend/agent/resources.py
> +    return from_dec - remainder
Aha! Good catch for that!

2022-03-23 08:21 UTC, achimnol approved these changes

2022-03-24 15:39 UTC, merged